import json
from pathlib import Path
from PyQt5.QtWidgets import (
    QWidget, QLabel, QVBoxLayout, QPushButton, QHBoxLayout,
    QTextEdit, QCheckBox, QComboBox, QMessageBox
)
from PyQt5.QtCore import Qt
import theme


def _make_theme_switch(parent: QWidget):
    try:
        return theme.AnimatedToggleSwitch(parent)
    except Exception:
        fallback = QCheckBox("", parent)
        fallback.setCursor(Qt.PointingHandCursor)
        return fallback


class ViewReportsWindow(QWidget):
    def __init__(self, worker_username, parent_window=None):
        super().__init__()
        self.worker_username = worker_username
        self.parent_window = parent_window
        self.setWindowTitle("View Reports")
        self.setMinimumSize(800, 600)
        
        self._init_ui()
        
        theme.sync_checkbox_to_theme(self.mode_switch)
        self.mode_label.setText(theme.theme_text())
    
    def _init_ui(self):
        # Header
        title_label = QLabel("Financial Reports", self)
        title_label.setStyleSheet("font-size: 18px; font-weight: 700;")
        
        self.mode_label = QLabel(theme.theme_text(), self)
        self.mode_label.setObjectName("modeLabel")
        
        self.mode_switch = _make_theme_switch(self)
        self.mode_switch.toggled.connect(self._toggle_mode)
        
        header_row = QHBoxLayout()
        header_row.addWidget(title_label)
        header_row.addStretch()
        header_row.addWidget(self.mode_label)
        header_row.addWidget(self.mode_switch)
        
        # Report selector
        selector_label = QLabel("Select Report Type:", self)
        
        self.report_selector = QComboBox(self)
        self.report_selector.addItems([
            "User Statistics",
            "Transaction Summary",
            "Loan Overview",
            "Account Balances",
            "Pending Verifications"
        ])
        self.report_selector.setMinimumHeight(35)
        
        # Generate button
        generate_btn = QPushButton("Generate Report", self)
        generate_btn.setObjectName("primary")
        generate_btn.setMinimumHeight(40)
        generate_btn.clicked.connect(self._generate_report)
        
        selector_row = QHBoxLayout()
        selector_row.addWidget(selector_label)
        selector_row.addWidget(self.report_selector)
        selector_row.addWidget(generate_btn)
        
        # Report display
        self.report_display = QTextEdit(self)
        self.report_display.setReadOnly(True)
        self.report_display.setPlaceholderText("Report will be displayed here...")
        
        # Buttons
        back_btn = QPushButton("Back", self)
        back_btn.clicked.connect(self._go_back)
        back_btn.setMinimumHeight(40)
        
        button_row = QHBoxLayout()
        button_row.addWidget(back_btn)
        button_row.addStretch()
        
        # Main layout
        main_layout = QVBoxLayout()
        main_layout.setSpacing(12)
        main_layout.setContentsMargins(20, 18, 20, 18)
        main_layout.addLayout(header_row)
        main_layout.addLayout(selector_row)
        main_layout.addWidget(self.report_display)
        main_layout.addLayout(button_row)
        
        self.setLayout(main_layout)
    
    def _generate_report(self):
        report_type = self.report_selector.currentText()
        
        if report_type == "User Statistics":
            self._generate_user_stats()
        elif report_type == "Transaction Summary":
            self._generate_transaction_summary()
        elif report_type == "Loan Overview":
            self._generate_loan_overview()
        elif report_type == "Account Balances":
            self._generate_account_balances()
        elif report_type == "Pending Verifications":
            self._generate_pending_verifications()
    
    def _generate_user_stats(self):
        users_file = Path(__file__).parent.parent / "user_app" / "users.json"
        try:
            with users_file.open("r", encoding="utf-8") as f:
                users = json.load(f)
            
            total = len(users)
            verified = sum(1 for u in users.values() if u.get("is_verified", False))
            unverified = total - verified
            
            report = f"""
╔════════════════════════════════════════╗
║         USER STATISTICS REPORT         ║
╚════════════════════════════════════════╝

Total Users: {total}
Verified Users: {verified}
Unverified Users: {unverified}
Verification Rate: {(verified/total*100) if total > 0 else 0:.1f}%

Generated by: {self.worker_username}
"""
            self.report_display.setPlainText(report)
        except Exception as e:
            QMessageBox.warning(self, "Error", f"Failed to generate report: {e}")
    
    def _generate_transaction_summary(self):
        report = f"""
╔════════════════════════════════════════╗
║      TRANSACTION SUMMARY REPORT        ║
╚════════════════════════════════════════╝

[Transaction data would be displayed here]

Total Transactions: N/A
Total Volume: N/A
Average Transaction: N/A

Generated by: {self.worker_username}
"""
        self.report_display.setPlainText(report)
    
    def _generate_loan_overview(self):
        loans_file = Path(__file__).parent / "loan_requests.json"
        try:
            with loans_file.open("r", encoding="utf-8") as f:
                loans = json.load(f)
            
            total = len(loans)
            pending = sum(1 for l in loans if isinstance(l, dict) and l.get("status") == "pending")
            approved = sum(1 for l in loans if isinstance(l, dict) and l.get("status") == "approved")
            rejected = sum(1 for l in loans if isinstance(l, dict) and l.get("status") == "rejected")
            
            report = f"""
╔════════════════════════════════════════╗
║         LOAN OVERVIEW REPORT           ║
╚════════════════════════════════════════╝

Total Loan Requests: {total}
Pending: {pending}
Approved: {approved}
Rejected: {rejected}

Approval Rate: {(approved/total*100) if total > 0 else 0:.1f}%

Generated by: {self.worker_username}
"""
            self.report_display.setPlainText(report)
        except Exception as e:
            QMessageBox.warning(self, "Error", f"Failed to generate report: {e}")
    
    def _generate_account_balances(self):
        users_file = Path(__file__).parent.parent / "user_app" / "users.json"
        try:
            with users_file.open("r", encoding="utf-8") as f:
                users = json.load(f)
            
            balances = [u.get("account_balance", 0) for u in users.values()]
            total_balance = sum(balances)
            avg_balance = total_balance / len(balances) if balances else 0
            max_balance = max(balances) if balances else 0
            min_balance = min(balances) if balances else 0
            
            report = f"""
╔════════════════════════════════════════╗
║      ACCOUNT BALANCES REPORT           ║
╚════════════════════════════════════════╝

Total Accounts: {len(users)}
Total Balance: {total_balance:,.2f} EGP
Average Balance: {avg_balance:,.2f} EGP
Highest Balance: {max_balance:,.2f} EGP
Lowest Balance: {min_balance:,.2f} EGP

Generated by: {self.worker_username}
"""
            self.report_display.setPlainText(report)
        except Exception as e:
            QMessageBox.warning(self, "Error", f"Failed to generate report: {e}")
    
    def _generate_pending_verifications(self):
        users_file = Path(__file__).parent.parent / "user_app" / "users.json"
        try:
            with users_file.open("r", encoding="utf-8") as f:
                users = json.load(f)
            
            pending_users = [email for email, data in users.items() if not data.get("is_verified", False)]
            
            report = f"""
╔════════════════════════════════════════╗
║    PENDING VERIFICATIONS REPORT        ║
╚════════════════════════════════════════╝

Total Pending: {len(pending_users)}

Pending User Accounts:
{''.join(f'  • {email}' + chr(10) for email in pending_users) if pending_users else '  (None)'}

Generated by: {self.worker_username}
"""
            self.report_display.setPlainText(report)
        except Exception as e:
            QMessageBox.warning(self, "Error", f"Failed to generate report: {e}")
    
    def _toggle_mode(self, checked):
        theme.set_global_theme(checked)
        self.mode_label.setText(theme.theme_text())
    
    def _go_back(self):
        if self.parent_window:
            self.parent_window.show()
        self.close()
